"""
LLM client helpers for the Flet chat (e.g. format_exception, chat filename suggestion).

Chat title/filename is generated by running the create_filename workflow
(assistants/create_filename.json) via run_create_filename_workflow() in workflow_designer_handler.
"""
from __future__ import annotations

from LLM_integrations import client as llm_client

__all__ = ["llm_client"]
