"""
Node-RED core node catalog: built-in node types in our format.

No Node-RED runtime dependency. Each entry: type name, input/output ports, optional
JavaScript code_template for export. When the assistant adds a unit with a type from
this catalog, we attach the template as the unit's code_block (language: javascript)
so the graph is convertible to Node-RED format. No JS executor in-app yet; code_block
is for canonical representation and export.

Prefer catalog generated by scripts/generate_node_red_catalog.py when @node-red/nodes
is installed (run scripts/install_node_red_and_generate_catalog.sh). Otherwise the
built-in hand-maintained catalog below is used.

Reference: https://nodered.org/docs/user-guide/nodes
"""

from __future__ import annotations

from typing import Any

from units.registry import UnitSpec, register_unit

# Prefer generated catalog from @node-red/nodes package when present.
try:
    from units.node_red._catalog_generated import NODE_RED_NODE_CATALOG
except ImportError:
    # Type name matches Node-RED (e.g. "inject", "function"). code_template: JS for export; empty for config-only nodes.
    NODE_RED_NODE_CATALOG = {
    "inject": {
        "input_ports": [],
        "output_ports": [("out", "Any")],
        "code_template": "",  # config-only (topic, payload, repeat)
    },
    "debug": {
        "input_ports": [("in", "Any")],
        "output_ports": [],
        "code_template": "",  # config-only (console output)
    },
    "function": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],
        "code_template": "// Node-RED function node\nreturn msg;",
    },
    "change": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],
        "code_template": "",  # config-only (set/move/delete rules)
    },
    "switch": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],  # multiple in Node-RED; we use single for simplicity
        "code_template": "",  # config-only (rules)
    },
    "split": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],
        "code_template": "",  # config: split by string/array/etc.
    },
    "join": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],
        "code_template": "",  # config: join mode
    },
    "template": {
        "input_ports": [("in", "Any")],
        "output_ports": [("out", "Any")],
        "code_template": "// Mustache/Handlebars template in params.template\nreturn msg;",
    },
}


def get_node_red_template(type_name: str) -> dict[str, Any] | None:
    """Return catalog entry for type_name (input_ports, output_ports, code_template) or None."""
    return NODE_RED_NODE_CATALOG.get(type_name)


def get_node_red_types() -> set[str]:
    """Return set of type names in the Node-RED catalog (for add_unit → canonical + code_block)."""
    return set(NODE_RED_NODE_CATALOG.keys())


def register_node_red_units() -> None:
    """Register each Node-RED catalog type as a UnitSpec (for Units Library when env=node_red)."""
    for type_name, entry in NODE_RED_NODE_CATALOG.items():
        in_ports = entry.get("input_ports") or []
        out_ports = entry.get("output_ports") or [("out", "Any")]
        register_unit(UnitSpec(
            type_name=type_name,
            input_ports=in_ports,
            output_ports=out_ports,
            step_fn=None,
            code_block_driven=True,  # no JS executor yet; code_block for canonical/export
            environment_tags=["node_red"],
            description=f"Node-RED core: {type_name} (JS code_block for export).",
        ))


def _register_node_red_env_loader() -> None:
    try:
        from units.env_loaders import register_env_loader
        register_env_loader("node_red", register_node_red_units)
    except Exception:
        pass


_register_node_red_env_loader()


__all__ = [
    "NODE_RED_NODE_CATALOG",
    "get_node_red_template",
    "get_node_red_types",
    "register_node_red_units",
]
